### ISSUE TITLE
Error: Network request failed

### ISSUE THREAD

**Issue by wtnldev** [DominicVonk/com.dovocode.freeathome#1]
Hello,

I succesfully installed the free@home homey app but I get this error on Settings Page:
Error: Network request failed
Error: Timed out after 30000ms.
The API is working if I manually send the request in Postman.
Any idea what I do wrong?

**Comment by DominicVonk** [comment]
I just pushed the latest version, can you let me know if it works now?

**Comment by wtnldev** [comment]
Thanks! It looks like the network error is gone now but the device are not found.
The message is: No new devices have been found.

**Comment by DominicVonk** [comment]
Can you manually restart the app in homey?

**Comment by wtnldev** [comment]
I just did but still no devices.

**Comment by wtnldev** [comment]
It looks like the problem is related to functionID in channels as I don't see any device in my free@home installation with functionID 7. I think in my installation it the functionID should be 12 for switch.

**Comment by DominicVonk** [comment]
Can you send me the dump of your devices from swagger?

**Comment by wtnldev** [comment]
I found a list of functionID's here [https://developer.eu.mybuildings.abb.com/fah_local/reference/functionids/](url) and now realize I don't have switch actuators but dimming actuators.

**Comment by wtnldev** [comment]
`{
    "devices": {
        "ABB7F59A686A": {
            "floor": "01",
            "room": "07",
            "interface": "RF",
            "displayName": "Sensor/dimaktor 1/1-voudig",
            "unresponsive": false,
            "channels": {
                "ch0000": {
                    "displayName": "Sensor/dimaktor 1/1-voudig",
                    "functionID": "1",
                    "inputs": {
                        "idp0000": {
                            "pairingID": 256,
                            "value": "0"
                        },
                        "idp0001": {
                            "pairingID": 18,
                            "value": "0"
                        },
                        "idp0002": {
                            "pairingID": 273,
                            "value": "0"
                        },
                        "idp0003": {
                            "pairingID": 257,
                            "value": "0"
                        },
                        "idp0004": {
                            "pairingID": 261,
                            "value": "0"
                        },
                        "idp0005": {
                            "pairingID": 278,
                            "value": "0"
                        },
                        "idp0006": {
                            "pairingID": 262,
                            "value": "0"
                        },
                        "idp0007": {
                            "pairingID": 1120,
                            "value": "0"
                        },
                        "idp0008": {
                            "pairingID": 61698,
                            "value": "0"
                        },
                        "idp0009": {
                            "pairingID": 272,
                            "value": "0"
                        },
                        "idp000a": {
                            "pairingID": 277,
                            "value": "0"
                        },
                        "idp000b": {
                            "pairingID": 354,
                            "value": "0"
                        },
                        "idp000c": {
                            "pairingID": 355,
                            "value": "0"
                        }
                    },
                    "outputs": {
                        "odp0000": {
                            "pairingID": 1,
                            "value": "0"
                        },
                        "odp0001": {
                            "pairingID": 16,
                            "value": "0"
                        },
                        "odp0002": {
                            "pairingID": 32,
                            "value": "0"
                        },
                        "odp0003": {
                            "pairingID": 33,
                            "value": "0"
                        },
                        "odp0004": {
                            "pairingID": 2,
                            "value": "0"
                        },
                        "odp0005": {
                            "pairingID": 3,
                            "value": "0"
                        },
                        "odp0006": {
                            "pairingID": 4,
                            "value": "0"
                        },
                        "odp0007": {
                            "pairingID": 40,
                            "value": "0"
                        },
                        "odp0008": {
                            "pairingID": 1088,
                            "value": "0"
                        },
                        "odp0009": {
                            "pairingID": 1089,
                            "value": "0"
                        },
                        "odp000a": {
                            "pairingID": 1090,
                            "value": "0"
                        },
                        "odp000b": {
                            "pairingID": 1091,
                            "value": "0"
                        },
                        "odp000c": {
                            "pairingID": 1094,
                            "value": "0"
                        },
                        "odp000d": {
                            "pairingID": 1098,
                            "value": "0"
                        },
                        "odp000e": {
                            "pairingID": 61697,
                            "value": "0"
                        },
                        "odp000f": {
                            "pairingID": 352,
                            "value": "0"
                        },
                        "odp0010": {
                            "pairingID": 353,
                            "value": "0"
                        }
                    }
                },
                "ch0008": {
                    "floor": "01",
                    "room": "07",
                    "displayName": "Spots",
                    "functionID": "12",
                    "inputs": {
                        "idp0000": {
                            "pairingID": 1,
                            "value": "0"
                        },
                        "idp0001": {
                            "pairingID": 16,
                            "value": "0"
                        },
                        "idp0002": {
                            "pairingID": 17,
                            "value": "0"
                        },
                        "idp0003": {
                            "pairingID": 2,
                            "value": "0"
                        },
                        "idp0004": {
                            "pairingID": 3,
                            "value": "0"
                        },
                        "idp0005": {
                            "pairingID": 4,
                            "value": "0"
                        },
                        "idp0006": {
                            "pairingID": 18,
                            "value": "0"
                        },
                        "idp0007": {
                            "pairingID": 6,
                            "value": "0"
                        }
                    },
                    "outputs": {
                        "odp0000": {
                            "pairingID": 256,
                            "value": "0"
                        },
                        "odp0001": {
                            "pairingID": 272,
                            "value": "0"
                        },
                        "odp0002": {
                            "pairingID": 273,
                            "value": "0"
                        },
                        "odp0003": {
                            "pairingID": 257,
                            "value": "0"
                        }
                    }
                },
                "ch000b": {
                    "displayName": "Sensor/dimaktor 1/1-voudig",
                    "functionID": "1",
                    "inputs": {
                        "idp0000": {
                            "pairingID": 256,
                            "value": "0"
                        },
                        "idp0001": {
                            "pairingID": 272,
                            "value": "0"
                        },
                        "idp0002": {
                            "pairingID": 354,
                            "value": "0"
                        },
                        "idp0003": {
                            "pairingID": 288,
                            "value": "0"
                        },
                        "idp0004": {
                            "pairingID": 257,
                            "value": "0"
                        },
                        "idp0005": {
                            "pairingID": 273,
                            "value": "0"
                        },
                        "idp0006": {
                            "pairingID": 261,
                            "value": "0"
                        },
                        "idp0007": {
                            "pairingID": 277,
                            "value": "0"
                        },
                        "idp0008": {
                            "pairingID": 355,
                            "value": "0"
                        },
                        "idp0009": {
                            "pairingID": 293,
                            "value": "0"
                        },
                        "idp000a": {
                            "pairingID": 262,
                            "value": "0"
                        },
                        "idp000b": {
                            "pairingID": 61698,
                            "value": "0"
                        },
                        "idp000c": {
                            "pairingID": 1120,
                            "value": "0"
                        }
                    },
                    "outputs": {
                        "odp0000": {
                            "pairingID": 1,
                            "value": "0"
                        },
                        "odp0001": {
                            "pairingID": 16,
                            "value": "0"
                        },
                        "odp0002": {
                            "pairingID": 352,
                            "value": "0"
                        },
                        "odp0003": {
                            "pairingID": 32,
                            "value": "0"
                        },
                        "odp0004": {
                            "pairingID": 33,
                            "value": "0"
                        },
                        "odp0005": {
                            "pairingID": 2,
                            "value": "0"
                        },
                        "odp0006": {
                            "pairingID": 3,
                            "value": "0"
                        },
                        "odp0007": {
                            "pairingID": 4,
                            "value": "0"
                        },
                        "odp0008": {
                            "pairingID": 40,
                            "value": "0"
                        },
                        "odp0009": {
                            "pairingID": 353,
                            "value": "0"
                        },
                        "odp000a": {
                            "pairingID": 61697,
                            "value": "0"
                        },
                        "odp000b": {
                            "pairingID": 1088,
                            "value": "0"
                        },
                        "odp000c": {
                            "pairingID": 1089,
                            "value": "0"
                        },
                        "odp000d": {
                            "pairingID": 1090,
                            "value": "0"
                        },
                        "odp000e": {
                            "pairingID": 1091,
                            "value": "0"
                        },
                        "odp000f": {
                            "pairingID": 1094,
                            "value": "0"
                        },
                        "odp0010": {
                            "pairingID": 1098,
                            "value": "0"
                        }
                    }
                }
            }
        }
    }
}`

**Comment by wtnldev** [comment]
[devices.txt](https://github.com/DominicVonk/com.dovocode.freeathome/files/8818540/devices.txt)

**Comment by DominicVonk** [comment]
I added functionID 12 now (Dimming actuator) can you pull this version and try again?

**Comment by wtnldev** [comment]
Yes it works! I now can switch on/off my dimming actuators. Thanks a lot!
