### ISSUE TITLE
Find no devices

### ISSUE THREAD

**Issue by no-public** [DominicVonk/com.dovocode.freeathome#2]
Hallo,
I am very happy that you have written a Hommey app for free@home.
But I can't find any devices with the homey app.
I don't get an error message.
In the configuration, I entered the ip address and a user with configuration rights.
The latest version is installed on the Homey Pro (Beta) and on the Free@Home controller.

**Comment by no-public** [comment]
I could find the problem.
The connection only works with the default user "installer".

**Comment by CTsio** [comment]
Hi,
I got the same issue with my Homey Pro & my Free@home. No devices found.
Here in The Netherlands the user is Installatie, which I used but cannot see my light switches.
Any suggestion what I'm doing wrong?
